language: go

go:
  - 1.12.x

before_install:
  - curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-x86_64.zip
  - unzip protoc-3.7.1-linux-x86_64.zip -d protoc3
  - mv protoc3/bin/* /usr/local/bin/
  - mv protoc3/include/* /usr/local/include/
  - rm -rfv protoc3
  - make dev-dependencies

script:
  - make check
